### ISSUE TITLE
Bot handles reaction *removed* events that happened prior to joining a channel

### ISSUE THREAD

**Issue by tmagrino** [Cornell-CIS-Slack/upbot#10]
Specific example is that I added and then removed an :arrow_up: (replace this with an actual upvote reaction) reaction, then invited upbot to the channel, and upbot then reacted to the removal retroactively.  Upbot should probably only react to events that have happened *after* joining the channel.

**Comment by gcr** [comment]
I'm not convinced this is a bug. Some people say @whatever++ and when nothing happens they invite upbot to the channel, which then counts the upvote properly.

**Comment by tmagrino** [comment]
You're right.  To be clearer, the issue isn't that if there's a vote prior to joining that it's seen.  The issue is that removing a vote (which is effectful in the current implementation for reaction events) is also seen and leads to what I think are not very intuitive behaviors.
